library(shiny)
library(DT)
library(shinyWidgets)
library(adhesiomeR)

data(adhesins_df)

shinyUI(navbarPage(title = "AdhesiomeR",
                   id = "adhesiomer",
                   tabPanel("Introduction",
                            textOutput("x"),
                            sidebarPanel(width = 5,
                                         includeMarkdown("intro.md")),
                            mainPanel(width = 7,
                                      "Table with adhesins in the database",
                                      dataTableOutput("adhesins"))),
                   tabPanel("Input & settings",
                            sidebarPanel(width = 6,
                                         h5(tags$b("Step 1.")),
                                         fileInput("seq_file", 
                                                   "Upload your genome file(s) in a FASTA format. You can process up to 100 files at once.",
                                                   multiple = TRUE
                                         ),
                                         h5(tags$b("Select number of threads used when running BLAST:")),
                                         numericInput("n_threads", 
                                                      label = NULL,
                                                      value = 1, 
                                                      min = 1, 
                                                      max = parallel::detectCores(logical = FALSE), 
                                                      width = "100px"),
                                         actionButton("blast", "Run BLAST!",
                                                      style="color: #fff; background-color: #337ab7; border-color: #2e6da4"),
                                         HTML("<hr>"),
                                         h5(tags$b("Step 2.")),
                                         pickerInput("systems",
                                                     "Select systems you want to analyse:",
                                                     choices = unique(adhesins_df[["System"]]),
                                                     selected = "Type 1 Fimbriae",
                                                     multiple = TRUE,
                                                     pickerOptions(actionsBox = TRUE,
                                                                   selectedTextFormat = 'count',
                                                                   countSelectedText = '{0} systems selected')),
                                         HTML("<hr>"),
                                         h5(tags$b("Select thresholds for gene presence: ")),
                                         fluidRow(column(4,
                                                         numericInput("identity", "Identity [%]",
                                                                      value = 70,
                                                                      min = 1,
                                                                      max = 100,
                                                                      step = 1,
                                                                      width = "100px")),
                                                  column(4,
                                                         numericInput("evalue", "E-value",
                                                                      value = prettyNum(1e-50, scientific = TRUE),
                                                                      min = 0,
                                                                      max = 1,
                                                                      width = "100px"))),
                                         HTML("<hr>"),
                                         h5(tags$b("Customise plot colors: ")),
                                         fluidRow(column(4,
                                                         textInput("presence_col", "Presence",
                                                                   value = "#e00e00",
                                                                   width = "100px")),
                                                  column(4,
                                                         textInput("absence_col", "Absence",
                                                                      value = "#85c1ff",
                                                                      width = "100px"))),
                                         actionButton("filtering_button", "Apply changes!",
                                                      style="color: #fff; background-color: #337ab7; border-color: #2e6da4"),
                            ),
                            mainPanel(width = 6,
                                      tableOutput("input_tab"))
                   ),
                   
                   tabPanel("Search results",
                            value = "blast_res",
                            dataTableOutput("blast_res")),
                   # tabPanel("Summary table",
                   #          dataTableOutput("presence_table"),
                   #          dataTableOutput("systems_summary_table")),
                   tabPanel("Summary plot",
                            value = "summary_plot",
                            checkboxInput("systems_summary_hide_missing",
                                                       "Hide systems not found in any genome.",
                                                       value = FALSE),
                            
                            plotOutput("systems_summary_plot")
                            ),
                   tabPanel("All genes plot",
                            value = "all_genes",
                            checkboxInput("all_genes_hide_missing",
                                          "Hide genes not found in any genome.",
                                          value = FALSE),
                            plotOutput("presence_plot")),
                   tabPanel("Systems plots",
                            value = "systems",
                            checkboxInput("systems_hide_missing",
                                          "Hide systems not found in any genome.",
                                          value = FALSE),
                            uiOutput("systems_plots")),
                   tabPanel("Report",
                            value = "report",
                            checkboxGroupInput("elements", 
                                               width = 900,
                                               "Select which elements you want to include in the report:",
                                               choices = c("Table with percents of genes found in each system" = "summary_table",
                                                           "Plot with percents of genes found in each system" = "summary_plot",
                                                           "Table with gene presence/absence" = "presence_table",
                                                           "Plot with gene presence/absence" = "presence_plot"),
                                               selected = c("summary_table", "summary_plot", "presence_table", "presence_plot")),
                            h5(tags$b("Options: ")),
                            checkboxInput("report_hide_genes",
                                          width = 900,
                                          "Hide genes that were not found in any genome.",
                                          value = FALSE),
                            checkboxInput("report_hide_systems",
                                          width = 900,
                                          "Hide systems that were not found in any genome.",
                                          value = FALSE),
                            downloadButton("download",
                                           "Download report"))
                   
                   
))
